package Perception;

import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

public class HomePanel extends javax.swing.JPanel {
    private CursorUtils cursor;
    
    public HomePanel() {
        initComponents();
        makePanel();
        makeShortCut();
    }
    
    private void makePanel(){
        cursor = new CursorUtils();
        
        String welcomeText = "Welcome " + SystemInit.myEval.getEvaluatorID();
        lblWelcome.setText(welcomeText);
        lblWelcome.setFont(new Font("Tahoma", Font.BOLD , 14));
    }
        
    private void makeShortCut(){
        btnEvaluateShortCut();
        btnSaveAndExitShortCut();
    }
    
    private void btnEvaluateShortCut() {
        Action evaluateButton = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                evaluateNow();
            }
        };

        KeyStroke key = KeyStroke.getKeyStroke(KeyEvent.VK_E, 0);
        InputMap inputMap = btnEvaluation.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ActionMap actionMap = btnEvaluation.getActionMap();
        inputMap.put(key, "Evaluation");
        actionMap.put("Evaluation", evaluateButton);

        btnEvaluation.setMnemonic(KeyEvent.VK_E);
    }

    private void btnSaveAndExitShortCut() {
        Action exitButton = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                saveAndExit();
            }
        };

        KeyStroke key = KeyStroke.getKeyStroke(KeyEvent.VK_S, 0);
        InputMap inputMap = btnExit.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ActionMap actionMap = btnExit.getActionMap();
        inputMap.put(key, "Exit");
        actionMap.put("Exit", exitButton);

        btnExit.setMnemonic(KeyEvent.VK_S);
    }
    
    private void evaluateNow() {
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        System.out.println("[HomePanel]  LastSeenSpeaker: " + SystemInit.myEval.getLastSeenSpeakerID() + " | LastSeenUtterance: " + SystemInit.myEval.getLastSeenUtterance());
        EvaluationPanel evalPane = new EvaluationPanel(SystemInit.myEval.getLastSeenSpeakerID(), SystemInit.myEval.getLastSeenUtterance());
        MainFrame.changePanel(evalPane);
    }
    
    private void saveAndExit(){
        MainFrame.saveAndExit();
//        MainFrame.layerUI.start();
////        Thread exitThread = new Thread(new SaveAndExitRunnable());
////        exitThread.start();
//        MainFrame.executor.execute(new SaveAndExitRunnable());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEvaluation = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblWelcome = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1000, 640));

        btnEvaluation.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnEvaluation.setText("Evaluate");
        btnEvaluation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEvaluationMouseClicked(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnExit.setText("Save and Exit");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });

        lblWelcome.setText("Welcome, ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(btnEvaluation, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(202, 202, 202)
                        .addComponent(btnExit)))
                .addContainerGap(198, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnEvaluation, btnExit});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEvaluation, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit))
                .addContainerGap(265, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnEvaluation, btnExit});

    }// </editor-fold>//GEN-END:initComponents


//  CHECK: LAST SEEN SPEAKER SHOULD ONLY BE ONE - SINCE ONLY DOING ONE FOLDER
    private void btnEvaluationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEvaluationMouseClicked
        evaluateNow();
    }//GEN-LAST:event_btnEvaluationMouseClicked

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        saveAndExit();
    }//GEN-LAST:event_btnExitMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEvaluation;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
